# Site setings
name: 'Ratón de Biblioteca'
description: 'Ratón de Biblioteca es un blog dedicado al diseño de software en el ecosistema Java.'
meta_description: 'programacion programación Java Spring patrones diseño arquitectura software metodologia metodología'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon2.ico'
baseurl:
production_url: ratondbiblioteca.com/
#disqus: 'justgoodthemes'
#mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'David Pérez'
  image: 'author_box_image.jpg'
  greetings: 'Ratón de Biblioteca'
  description: "Notas de programación, buenas prácticas y diseño de software"
  bio: 'Psicólogo de corazón, informático de profesión, llevo más de veinte años dedicado al desarrollo de software en los que me he especializado en el ecosistema Java/Spring'

# Contact form setings
email: david.perez.rod@gmx.es
contact_page_description: "Esteré encantado de recibir cualquier sugerencia, corrección, o propuesta. Si hay algo que quieras comentarme, ponte en contacto conmigo a través del siguiente formulario."
thankyou_page_description: "Tu mensaje se envió correctamente."

# Social links
#twitter: 'username'
#facebook: 'username'
github: 'DavidPerezRod'
#codepen: 'username'
#dribbble: 'username'
#medium: '@username'
#instagram: 'username'
#pinterest: 'username'
linkedin: 'dabizme'
#producthunt: '@username'

# Navigation 
navigation:
  - text: About
    url: /about/
#  - text: Style Guide
#    url: /style-guide/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
